// Minimal client-side subset of the upstream OpenShell gateway's
// openshell.v1.OpenShell gRPC service (github.com/nvidia/openshell,
// proto/openshell.proto + proto/datamodel.proto + proto/sandbox.proto at the
// pinned tag hack/openshell-pins references) — only the RPCs and messages
// OGO's controllers actually call: workspace membership, provider
// credentials, and the gateway-global policy lock.
//
// A gRPC client only needs matching method paths and request/response
// message shapes for the RPCs it calls; it doesn't need the rest of the
// service's ~50 other RPCs (sandboxes, drafts, inference, etc.) declared
// there. Field numbers/types below are copied verbatim from upstream to
// preserve wire compatibility — do not renumber. Upstream's per-method
// `option (openshell.options.v1.authorization)` annotations are server-side
// authorization config, not needed by a client, and are omitted; see
// crates/openshell-server/src/auth/ upstream for the real requirement (every
// RPC here requires a Bearer token with the configured admin_role -- the
// same "openshell-admin" role satisfies workspace-admin, provider-admin, and
// platform-admin/global-policy checks alike, confirmed by direct source
// read, not merely inferred).
//
// All new messages below (Provider* and the policy/SandboxPolicy family)
// intentionally omit fields OGO's controllers never set or read -- e.g.
// Provider.credential_expires_at_ms/profile_workspace (refresh-managed
// credentials and multi-workspace profiles, out of scope),
// SandboxPolicy.landlock/network_middlewares (no CRD equivalent),
// NetworkEndpoint's ~18 L7/GraphQL/MCP/SigV4 fields beyond the 5 the
// existing OpenShellPolicy CRD already exposes. proto3 unknown-field
// semantics make omitting a real field safe on both encode and decode.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openshell.proto

package openshellclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workspace-scoped role for members.
type WorkspaceRole int32

const (
	WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED WorkspaceRole = 0
	WorkspaceRole_WORKSPACE_ROLE_USER        WorkspaceRole = 1
	WorkspaceRole_WORKSPACE_ROLE_ADMIN       WorkspaceRole = 2
)

// Enum value maps for WorkspaceRole.
var (
	WorkspaceRole_name = map[int32]string{
		0: "WORKSPACE_ROLE_UNSPECIFIED",
		1: "WORKSPACE_ROLE_USER",
		2: "WORKSPACE_ROLE_ADMIN",
	}
	WorkspaceRole_value = map[string]int32{
		"WORKSPACE_ROLE_UNSPECIFIED": 0,
		"WORKSPACE_ROLE_USER":        1,
		"WORKSPACE_ROLE_ADMIN":       2,
	}
)

func (x WorkspaceRole) Enum() *WorkspaceRole {
	p := new(WorkspaceRole)
	*p = x
	return p
}

func (x WorkspaceRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceRole) Descriptor() protoreflect.EnumDescriptor {
	return file_openshell_proto_enumTypes[0].Descriptor()
}

func (WorkspaceRole) Type() protoreflect.EnumType {
	return &file_openshell_proto_enumTypes[0]
}

func (x WorkspaceRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceRole.Descriptor instead.
func (WorkspaceRole) EnumDescriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{0}
}

// Kubernetes-style metadata shared by all top-level OpenShell domain
// objects. Verbatim copy of openshell.datamodel.v1.ObjectMeta.
type ObjectMeta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAtMs         int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	Labels              map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceVersion     uint64                 `protobuf:"varint,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Annotations         map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workspace           string                 `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	DeletionTimestampMs int64                  `protobuf:"varint,8,opt,name=deletion_timestamp_ms,json=deletionTimestampMs,proto3" json:"deletion_timestamp_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_openshell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetResourceVersion() uint64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ObjectMeta) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ObjectMeta) GetDeletionTimestampMs() int64 {
	if x != nil {
		return x.DeletionTimestampMs
	}
	return 0
}

// Workspace membership record.
type WorkspaceMember struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// OIDC subject claim identifying the principal.
	PrincipalSubject string        `protobuf:"bytes,2,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	Role             WorkspaceRole `protobuf:"varint,3,opt,name=role,proto3,enum=openshell.v1.WorkspaceRole" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkspaceMember) Reset() {
	*x = WorkspaceMember{}
	mi := &file_openshell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMember) ProtoMessage() {}

func (x *WorkspaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMember.ProtoReflect.Descriptor instead.
func (*WorkspaceMember) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceMember) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkspaceMember) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

func (x *WorkspaceMember) GetRole() WorkspaceRole {
	if x != nil {
		return x.Role
	}
	return WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED
}

type AddWorkspaceMemberRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	PrincipalSubject string                 `protobuf:"bytes,2,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	Role             WorkspaceRole          `protobuf:"varint,3,opt,name=role,proto3,enum=openshell.v1.WorkspaceRole" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddWorkspaceMemberRequest) Reset() {
	*x = AddWorkspaceMemberRequest{}
	mi := &file_openshell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkspaceMemberRequest) ProtoMessage() {}

func (x *AddWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*AddWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{2}
}

func (x *AddWorkspaceMemberRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *AddWorkspaceMemberRequest) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

func (x *AddWorkspaceMemberRequest) GetRole() WorkspaceRole {
	if x != nil {
		return x.Role
	}
	return WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED
}

type AddWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *WorkspaceMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkspaceMemberResponse) Reset() {
	*x = AddWorkspaceMemberResponse{}
	mi := &file_openshell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkspaceMemberResponse) ProtoMessage() {}

func (x *AddWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*AddWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{3}
}

func (x *AddWorkspaceMemberResponse) GetMember() *WorkspaceMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveWorkspaceMemberRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	PrincipalSubject string                 `protobuf:"bytes,2,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveWorkspaceMemberRequest) Reset() {
	*x = RemoveWorkspaceMemberRequest{}
	mi := &file_openshell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkspaceMemberRequest) ProtoMessage() {}

func (x *RemoveWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveWorkspaceMemberRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *RemoveWorkspaceMemberRequest) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

type RemoveWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkspaceMemberResponse) Reset() {
	*x = RemoveWorkspaceMemberResponse{}
	mi := &file_openshell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkspaceMemberResponse) ProtoMessage() {}

func (x *RemoveWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveWorkspaceMemberResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListWorkspaceMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersRequest) Reset() {
	*x = ListWorkspaceMembersRequest{}
	mi := &file_openshell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersRequest) ProtoMessage() {}

func (x *ListWorkspaceMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkspaceMembersRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ListWorkspaceMembersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkspaceMembersRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorkspaceMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*WorkspaceMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersResponse) Reset() {
	*x = ListWorkspaceMembersResponse{}
	mi := &file_openshell_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersResponse) ProtoMessage() {}

func (x *ListWorkspaceMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkspaceMembersResponse) GetMembers() []*WorkspaceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// Provider model, verbatim subset of openshell.datamodel.v1.Provider
// (proto/datamodel.proto:71-88 upstream). Field numbers 5 (
// credential_expires_at_ms) and 6 (profile_workspace) intentionally
// skipped -- not set or read by OGO's controller.
type Provider struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type     string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Env-var-name -> value. Upsert-or-leave-untouched on Update: a key with a
	// non-empty value is set, a key with an empty string value is deleted, a
	// key omitted entirely from the request is left unchanged server-side.
	Credentials map[string]string `protobuf:"bytes,3,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Same upsert/leave-untouched/empty-string-deletes semantics as credentials.
	Config        map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_openshell_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{8}
}

func (x *Provider) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Provider) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_openshell_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{9}
}

func (x *CreateProviderRequest) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *CreateProviderRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type UpdateProviderRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Field 2 (credential_expires_at_ms) intentionally skipped, see Provider.
	Workspace     string `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_openshell_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProviderRequest) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *UpdateProviderRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type DeleteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderRequest) Reset() {
	*x = DeleteProviderRequest{}
	mi := &file_openshell_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderRequest) ProtoMessage() {}

func (x *DeleteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteProviderRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type DeleteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderResponse) Reset() {
	*x = DeleteProviderResponse{}
	mi := &file_openshell_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderResponse) ProtoMessage() {}

func (x *DeleteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProviderResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderResponse) Reset() {
	*x = ProviderResponse{}
	mi := &file_openshell_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderResponse) ProtoMessage() {}

func (x *ProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderResponse.ProtoReflect.Descriptor instead.
func (*ProviderResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{13}
}

func (x *ProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// Verbatim subset of openshell.sandbox.v1.FilesystemPolicy
// (proto/sandbox.proto:35-42 upstream).
type FilesystemPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeWorkdir bool                   `protobuf:"varint,1,opt,name=include_workdir,json=includeWorkdir,proto3" json:"include_workdir,omitempty"`
	ReadOnly       []string               `protobuf:"bytes,2,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ReadWrite      []string               `protobuf:"bytes,3,rep,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilesystemPolicy) Reset() {
	*x = FilesystemPolicy{}
	mi := &file_openshell_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPolicy) ProtoMessage() {}

func (x *FilesystemPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPolicy.ProtoReflect.Descriptor instead.
func (*FilesystemPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{14}
}

func (x *FilesystemPolicy) GetIncludeWorkdir() bool {
	if x != nil {
		return x.IncludeWorkdir
	}
	return false
}

func (x *FilesystemPolicy) GetReadOnly() []string {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *FilesystemPolicy) GetReadWrite() []string {
	if x != nil {
		return x.ReadWrite
	}
	return nil
}

// Verbatim subset of openshell.sandbox.v1.ProcessPolicy
// (proto/sandbox.proto:51-57 upstream).
type ProcessPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunAsUser     string                 `protobuf:"bytes,1,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	RunAsGroup    string                 `protobuf:"bytes,2,opt,name=run_as_group,json=runAsGroup,proto3" json:"run_as_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPolicy) Reset() {
	*x = ProcessPolicy{}
	mi := &file_openshell_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPolicy) ProtoMessage() {}

func (x *ProcessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPolicy.ProtoReflect.Descriptor instead.
func (*ProcessPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessPolicy) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *ProcessPolicy) GetRunAsGroup() string {
	if x != nil {
		return x.RunAsGroup
	}
	return ""
}

// Verbatim subset of openshell.sandbox.v1.NetworkBinary
// (proto/sandbox.proto:289-293 upstream). Field 2 (harness) is
// upstream-deprecated and skipped.
type NetworkBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinary) Reset() {
	*x = NetworkBinary{}
	mi := &file_openshell_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinary) ProtoMessage() {}

func (x *NetworkBinary) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinary.ProtoReflect.Descriptor instead.
func (*NetworkBinary) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Subset of openshell.sandbox.v1.NetworkEndpoint (proto/sandbox.proto:97-178
// upstream) -- only the 5 fields OGO's OpenShellPolicy CRD exposes today
// (host, port, protocol, enforcement, access). Field 4 (tls) and fields
// 7-23 (explicit L7 allow/deny rules, allowed_ips, multi-port, GraphQL,
// path scoping, credential rewriting, SigV4 signing, MCP options) are
// intentionally skipped -- no CRD equivalent, not a regression since the
// CRD never exposed them.
type NetworkEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// uint32, matching upstream exactly -- not int32.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Enforcement   string `protobuf:"bytes,5,opt,name=enforcement,proto3" json:"enforcement,omitempty"`
	Access        string `protobuf:"bytes,6,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_openshell_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{17}
}

func (x *NetworkEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEndpoint) GetEnforcement() string {
	if x != nil {
		return x.Enforcement
	}
	return ""
}

func (x *NetworkEndpoint) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

// Verbatim subset of openshell.sandbox.v1.NetworkPolicyRule
// (proto/sandbox.proto:59-66 upstream). The map key (in SandboxPolicy,
// below) is authoritative for addressing a rule; name is a cosmetic label.
type NetworkPolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints     []*NetworkEndpoint     `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Binaries      []*NetworkBinary       `protobuf:"bytes,3,rep,name=binaries,proto3" json:"binaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_openshell_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{18}
}

func (x *NetworkPolicyRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyRule) GetEndpoints() []*NetworkEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkPolicyRule) GetBinaries() []*NetworkBinary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

// Subset of openshell.sandbox.v1.SandboxPolicy (proto/sandbox.proto:18-31
// upstream). Field 1 (version) is server-assigned and skipped. Field 3
// (landlock) and field 6 (network_middlewares) have no OpenShellPolicy CRD
// equivalent and are skipped -- server defaults apply when omitted.
type SandboxPolicy struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Filesystem      *FilesystemPolicy             `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Process         *ProcessPolicy                `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	NetworkPolicies map[string]*NetworkPolicyRule `protobuf:"bytes,5,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_openshell_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{19}
}

func (x *SandboxPolicy) GetFilesystem() *FilesystemPolicy {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *SandboxPolicy) GetProcess() *ProcessPolicy {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkPolicies() map[string]*NetworkPolicyRule {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

// Subset of UpdateConfigRequest (proto/openshell.proto:1747-1785 upstream).
// OGO only ever uses this at global=true scope: name is always empty,
// merge_operations/expected_resource_version/annotations (fields 7-9) are
// unused (merge ops are rejected server-side for global scope anyway; no
// CAS or annotation use case exists for a gateway-wide policy push).
type UpdateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox name; always empty for OGO's global-only usage.
	Name   string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Policy *SandboxPolicy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// Set to "policy" for the delete-global-policy path only.
	SettingKey    string `protobuf:"bytes,3,opt,name=setting_key,json=settingKey,proto3" json:"setting_key,omitempty"`
	DeleteSetting bool   `protobuf:"varint,5,opt,name=delete_setting,json=deleteSetting,proto3" json:"delete_setting,omitempty"`
	// Always true for OGO -- gateway-wide policy, never sandbox-scoped.
	Global        bool   `protobuf:"varint,6,opt,name=global,proto3" json:"global,omitempty"`
	Workspace     string `protobuf:"bytes,10,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_openshell_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConfigRequest) GetPolicy() *SandboxPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UpdateConfigRequest) GetSettingKey() string {
	if x != nil {
		return x.SettingKey
	}
	return ""
}

func (x *UpdateConfigRequest) GetDeleteSetting() bool {
	if x != nil {
		return x.DeleteSetting
	}
	return false
}

func (x *UpdateConfigRequest) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

func (x *UpdateConfigRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

// Subset of UpdateConfigResponse (proto/openshell.proto:1832-1843 upstream).
// Field 5 (annotations) is skipped -- always empty for global updates.
type UpdateConfigResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PolicyHash       string                 `protobuf:"bytes,2,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	SettingsRevision uint64                 `protobuf:"varint,3,opt,name=settings_revision,json=settingsRevision,proto3" json:"settings_revision,omitempty"`
	Deleted          bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_openshell_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateConfigResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateConfigResponse) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *UpdateConfigResponse) GetSettingsRevision() uint64 {
	if x != nil {
		return x.SettingsRevision
	}
	return 0
}

func (x *UpdateConfigResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_openshell_proto protoreflect.FileDescriptor

const file_openshell_proto_rawDesc = "" +
	"\n" +
	"\x0fopenshell.proto\x12\fopenshell.v1\"\xd7\x03\n" +
	"\n" +
	"ObjectMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12<\n" +
	"\x06labels\x18\x04 \x03(\v2$.openshell.v1.ObjectMeta.LabelsEntryR\x06labels\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\x04R\x0fresourceVersion\x12K\n" +
	"\vannotations\x18\x06 \x03(\v2).openshell.v1.ObjectMeta.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\x122\n" +
	"\x15deletion_timestamp_ms\x18\b \x01(\x03R\x13deletionTimestampMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x0fWorkspaceMember\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.openshell.v1.ObjectMetaR\bmetadata\x12+\n" +
	"\x11principal_subject\x18\x02 \x01(\tR\x10principalSubject\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.openshell.v1.WorkspaceRoleR\x04role\"\x97\x01\n" +
	"\x19AddWorkspaceMemberRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12+\n" +
	"\x11principal_subject\x18\x02 \x01(\tR\x10principalSubject\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.openshell.v1.WorkspaceRoleR\x04role\"S\n" +
	"\x1aAddWorkspaceMemberResponse\x125\n" +
	"\x06member\x18\x01 \x01(\v2\x1d.openshell.v1.WorkspaceMemberR\x06member\"i\n" +
	"\x1cRemoveWorkspaceMemberRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12+\n" +
	"\x11principal_subject\x18\x02 \x01(\tR\x10principalSubject\"9\n" +
	"\x1dRemoveWorkspaceMemberResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"i\n" +
	"\x1bListWorkspaceMembersRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"W\n" +
	"\x1cListWorkspaceMembersResponse\x127\n" +
	"\amembers\x18\x01 \x03(\v2\x1d.openshell.v1.WorkspaceMemberR\amembers\"\xd6\x02\n" +
	"\bProvider\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.openshell.v1.ObjectMetaR\bmetadata\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12I\n" +
	"\vcredentials\x18\x03 \x03(\v2'.openshell.v1.Provider.CredentialsEntryR\vcredentials\x12:\n" +
	"\x06config\x18\x04 \x03(\v2\".openshell.v1.Provider.ConfigEntryR\x06config\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x15CreateProviderRequest\x122\n" +
	"\bprovider\x18\x01 \x01(\v2\x16.openshell.v1.ProviderR\bprovider\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"i\n" +
	"\x15UpdateProviderRequest\x122\n" +
	"\bprovider\x18\x01 \x01(\v2\x16.openshell.v1.ProviderR\bprovider\x12\x1c\n" +
	"\tworkspace\x18\x03 \x01(\tR\tworkspace\"I\n" +
	"\x15DeleteProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"2\n" +
	"\x16DeleteProviderResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"F\n" +
	"\x10ProviderResponse\x122\n" +
	"\bprovider\x18\x01 \x01(\v2\x16.openshell.v1.ProviderR\bprovider\"w\n" +
	"\x10FilesystemPolicy\x12'\n" +
	"\x0finclude_workdir\x18\x01 \x01(\bR\x0eincludeWorkdir\x12\x1b\n" +
	"\tread_only\x18\x02 \x03(\tR\breadOnly\x12\x1d\n" +
	"\n" +
	"read_write\x18\x03 \x03(\tR\treadWrite\"Q\n" +
	"\rProcessPolicy\x12\x1e\n" +
	"\vrun_as_user\x18\x01 \x01(\tR\trunAsUser\x12 \n" +
	"\frun_as_group\x18\x02 \x01(\tR\n" +
	"runAsGroup\"#\n" +
	"\rNetworkBinary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x8f\x01\n" +
	"\x0fNetworkEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12 \n" +
	"\venforcement\x18\x05 \x01(\tR\venforcement\x12\x16\n" +
	"\x06access\x18\x06 \x01(\tR\x06access\"\x9d\x01\n" +
	"\x11NetworkPolicyRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\tendpoints\x18\x02 \x03(\v2\x1d.openshell.v1.NetworkEndpointR\tendpoints\x127\n" +
	"\bbinaries\x18\x03 \x03(\v2\x1b.openshell.v1.NetworkBinaryR\bbinaries\"\xc8\x02\n" +
	"\rSandboxPolicy\x12>\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\v2\x1e.openshell.v1.FilesystemPolicyR\n" +
	"filesystem\x125\n" +
	"\aprocess\x18\x04 \x01(\v2\x1b.openshell.v1.ProcessPolicyR\aprocess\x12[\n" +
	"\x10network_policies\x18\x05 \x03(\v20.openshell.v1.SandboxPolicy.NetworkPoliciesEntryR\x0fnetworkPolicies\x1ac\n" +
	"\x14NetworkPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.openshell.v1.NetworkPolicyRuleR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x13UpdateConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x06policy\x18\x02 \x01(\v2\x1b.openshell.v1.SandboxPolicyR\x06policy\x12\x1f\n" +
	"\vsetting_key\x18\x03 \x01(\tR\n" +
	"settingKey\x12%\n" +
	"\x0edelete_setting\x18\x05 \x01(\bR\rdeleteSetting\x12\x16\n" +
	"\x06global\x18\x06 \x01(\bR\x06global\x12\x1c\n" +
	"\tworkspace\x18\n" +
	" \x01(\tR\tworkspace\"\x98\x01\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1f\n" +
	"\vpolicy_hash\x18\x02 \x01(\tR\n" +
	"policyHash\x12+\n" +
	"\x11settings_revision\x18\x03 \x01(\x04R\x10settingsRevision\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted*b\n" +
	"\rWorkspaceRole\x12\x1e\n" +
	"\x1aWORKSPACE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WORKSPACE_ROLE_USER\x10\x01\x12\x18\n" +
	"\x14WORKSPACE_ROLE_ADMIN\x10\x022\xb7\x05\n" +
	"\tOpenShell\x12g\n" +
	"\x12AddWorkspaceMember\x12'.openshell.v1.AddWorkspaceMemberRequest\x1a(.openshell.v1.AddWorkspaceMemberResponse\x12p\n" +
	"\x15RemoveWorkspaceMember\x12*.openshell.v1.RemoveWorkspaceMemberRequest\x1a+.openshell.v1.RemoveWorkspaceMemberResponse\x12m\n" +
	"\x14ListWorkspaceMembers\x12).openshell.v1.ListWorkspaceMembersRequest\x1a*.openshell.v1.ListWorkspaceMembersResponse\x12U\n" +
	"\x0eCreateProvider\x12#.openshell.v1.CreateProviderRequest\x1a\x1e.openshell.v1.ProviderResponse\x12U\n" +
	"\x0eUpdateProvider\x12#.openshell.v1.UpdateProviderRequest\x1a\x1e.openshell.v1.ProviderResponse\x12[\n" +
	"\x0eDeleteProvider\x12#.openshell.v1.DeleteProviderRequest\x1a$.openshell.v1.DeleteProviderResponse\x12U\n" +
	"\fUpdateConfig\x12!.openshell.v1.UpdateConfigRequest\x1a\".openshell.v1.UpdateConfigResponseBBZ@github.com/aknochow/ogo/internal/openshellclient;openshellclientb\x06proto3"

var (
	file_openshell_proto_rawDescOnce sync.Once
	file_openshell_proto_rawDescData []byte
)

func file_openshell_proto_rawDescGZIP() []byte {
	file_openshell_proto_rawDescOnce.Do(func() {
		file_openshell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_proto_rawDesc), len(file_openshell_proto_rawDesc)))
	})
	return file_openshell_proto_rawDescData
}

var file_openshell_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openshell_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_openshell_proto_goTypes = []any{
	(WorkspaceRole)(0),                    // 0: openshell.v1.WorkspaceRole
	(*ObjectMeta)(nil),                    // 1: openshell.v1.ObjectMeta
	(*WorkspaceMember)(nil),               // 2: openshell.v1.WorkspaceMember
	(*AddWorkspaceMemberRequest)(nil),     // 3: openshell.v1.AddWorkspaceMemberRequest
	(*AddWorkspaceMemberResponse)(nil),    // 4: openshell.v1.AddWorkspaceMemberResponse
	(*RemoveWorkspaceMemberRequest)(nil),  // 5: openshell.v1.RemoveWorkspaceMemberRequest
	(*RemoveWorkspaceMemberResponse)(nil), // 6: openshell.v1.RemoveWorkspaceMemberResponse
	(*ListWorkspaceMembersRequest)(nil),   // 7: openshell.v1.ListWorkspaceMembersRequest
	(*ListWorkspaceMembersResponse)(nil),  // 8: openshell.v1.ListWorkspaceMembersResponse
	(*Provider)(nil),                      // 9: openshell.v1.Provider
	(*CreateProviderRequest)(nil),         // 10: openshell.v1.CreateProviderRequest
	(*UpdateProviderRequest)(nil),         // 11: openshell.v1.UpdateProviderRequest
	(*DeleteProviderRequest)(nil),         // 12: openshell.v1.DeleteProviderRequest
	(*DeleteProviderResponse)(nil),        // 13: openshell.v1.DeleteProviderResponse
	(*ProviderResponse)(nil),              // 14: openshell.v1.ProviderResponse
	(*FilesystemPolicy)(nil),              // 15: openshell.v1.FilesystemPolicy
	(*ProcessPolicy)(nil),                 // 16: openshell.v1.ProcessPolicy
	(*NetworkBinary)(nil),                 // 17: openshell.v1.NetworkBinary
	(*NetworkEndpoint)(nil),               // 18: openshell.v1.NetworkEndpoint
	(*NetworkPolicyRule)(nil),             // 19: openshell.v1.NetworkPolicyRule
	(*SandboxPolicy)(nil),                 // 20: openshell.v1.SandboxPolicy
	(*UpdateConfigRequest)(nil),           // 21: openshell.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),          // 22: openshell.v1.UpdateConfigResponse
	nil,                                   // 23: openshell.v1.ObjectMeta.LabelsEntry
	nil,                                   // 24: openshell.v1.ObjectMeta.AnnotationsEntry
	nil,                                   // 25: openshell.v1.Provider.CredentialsEntry
	nil,                                   // 26: openshell.v1.Provider.ConfigEntry
	nil,                                   // 27: openshell.v1.SandboxPolicy.NetworkPoliciesEntry
}
var file_openshell_proto_depIdxs = []int32{
	23, // 0: openshell.v1.ObjectMeta.labels:type_name -> openshell.v1.ObjectMeta.LabelsEntry
	24, // 1: openshell.v1.ObjectMeta.annotations:type_name -> openshell.v1.ObjectMeta.AnnotationsEntry
	1,  // 2: openshell.v1.WorkspaceMember.metadata:type_name -> openshell.v1.ObjectMeta
	0,  // 3: openshell.v1.WorkspaceMember.role:type_name -> openshell.v1.WorkspaceRole
	0,  // 4: openshell.v1.AddWorkspaceMemberRequest.role:type_name -> openshell.v1.WorkspaceRole
	2,  // 5: openshell.v1.AddWorkspaceMemberResponse.member:type_name -> openshell.v1.WorkspaceMember
	2,  // 6: openshell.v1.ListWorkspaceMembersResponse.members:type_name -> openshell.v1.WorkspaceMember
	1,  // 7: openshell.v1.Provider.metadata:type_name -> openshell.v1.ObjectMeta
	25, // 8: openshell.v1.Provider.credentials:type_name -> openshell.v1.Provider.CredentialsEntry
	26, // 9: openshell.v1.Provider.config:type_name -> openshell.v1.Provider.ConfigEntry
	9,  // 10: openshell.v1.CreateProviderRequest.provider:type_name -> openshell.v1.Provider
	9,  // 11: openshell.v1.UpdateProviderRequest.provider:type_name -> openshell.v1.Provider
	9,  // 12: openshell.v1.ProviderResponse.provider:type_name -> openshell.v1.Provider
	18, // 13: openshell.v1.NetworkPolicyRule.endpoints:type_name -> openshell.v1.NetworkEndpoint
	17, // 14: openshell.v1.NetworkPolicyRule.binaries:type_name -> openshell.v1.NetworkBinary
	15, // 15: openshell.v1.SandboxPolicy.filesystem:type_name -> openshell.v1.FilesystemPolicy
	16, // 16: openshell.v1.SandboxPolicy.process:type_name -> openshell.v1.ProcessPolicy
	27, // 17: openshell.v1.SandboxPolicy.network_policies:type_name -> openshell.v1.SandboxPolicy.NetworkPoliciesEntry
	20, // 18: openshell.v1.UpdateConfigRequest.policy:type_name -> openshell.v1.SandboxPolicy
	19, // 19: openshell.v1.SandboxPolicy.NetworkPoliciesEntry.value:type_name -> openshell.v1.NetworkPolicyRule
	3,  // 20: openshell.v1.OpenShell.AddWorkspaceMember:input_type -> openshell.v1.AddWorkspaceMemberRequest
	5,  // 21: openshell.v1.OpenShell.RemoveWorkspaceMember:input_type -> openshell.v1.RemoveWorkspaceMemberRequest
	7,  // 22: openshell.v1.OpenShell.ListWorkspaceMembers:input_type -> openshell.v1.ListWorkspaceMembersRequest
	10, // 23: openshell.v1.OpenShell.CreateProvider:input_type -> openshell.v1.CreateProviderRequest
	11, // 24: openshell.v1.OpenShell.UpdateProvider:input_type -> openshell.v1.UpdateProviderRequest
	12, // 25: openshell.v1.OpenShell.DeleteProvider:input_type -> openshell.v1.DeleteProviderRequest
	21, // 26: openshell.v1.OpenShell.UpdateConfig:input_type -> openshell.v1.UpdateConfigRequest
	4,  // 27: openshell.v1.OpenShell.AddWorkspaceMember:output_type -> openshell.v1.AddWorkspaceMemberResponse
	6,  // 28: openshell.v1.OpenShell.RemoveWorkspaceMember:output_type -> openshell.v1.RemoveWorkspaceMemberResponse
	8,  // 29: openshell.v1.OpenShell.ListWorkspaceMembers:output_type -> openshell.v1.ListWorkspaceMembersResponse
	14, // 30: openshell.v1.OpenShell.CreateProvider:output_type -> openshell.v1.ProviderResponse
	14, // 31: openshell.v1.OpenShell.UpdateProvider:output_type -> openshell.v1.ProviderResponse
	13, // 32: openshell.v1.OpenShell.DeleteProvider:output_type -> openshell.v1.DeleteProviderResponse
	22, // 33: openshell.v1.OpenShell.UpdateConfig:output_type -> openshell.v1.UpdateConfigResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_openshell_proto_init() }
func file_openshell_proto_init() {
	if File_openshell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_proto_rawDesc), len(file_openshell_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openshell_proto_goTypes,
		DependencyIndexes: file_openshell_proto_depIdxs,
		EnumInfos:         file_openshell_proto_enumTypes,
		MessageInfos:      file_openshell_proto_msgTypes,
	}.Build()
	File_openshell_proto = out.File
	file_openshell_proto_goTypes = nil
	file_openshell_proto_depIdxs = nil
}
