// Minimal client-side subset of the upstream OpenShell gateway's
// openshell.v1.OpenShell gRPC service (github.com/nvidia/openshell,
// proto/openshell.proto + proto/datamodel.proto at the pinned tag
// hack/openshell-pins references) — only the workspace-membership RPCs
// and messages OGO's controller actually calls.
//
// A gRPC client only needs matching method paths and request/response
// message shapes for the RPCs it calls; it doesn't need the rest of the
// service's ~50 other RPCs (sandboxes, providers, drafts, inference,
// etc.) declared here. Field numbers/types below are copied verbatim
// from upstream to preserve wire compatibility — do not renumber.
// Upstream's per-method `option (openshell.options.v1.authorization)`
// annotations are server-side authorization config, not needed by a
// client, and are omitted; see openshell.proto for the real
// requirement (workspace RPCs require a Bearer token with the admin
// role and no explicit scope check today — see
// crates/openshell-server/src/grpc/mod.rs upstream).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace.proto

package openshellclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workspace-scoped role for members.
type WorkspaceRole int32

const (
	WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED WorkspaceRole = 0
	WorkspaceRole_WORKSPACE_ROLE_USER        WorkspaceRole = 1
	WorkspaceRole_WORKSPACE_ROLE_ADMIN       WorkspaceRole = 2
)

// Enum value maps for WorkspaceRole.
var (
	WorkspaceRole_name = map[int32]string{
		0: "WORKSPACE_ROLE_UNSPECIFIED",
		1: "WORKSPACE_ROLE_USER",
		2: "WORKSPACE_ROLE_ADMIN",
	}
	WorkspaceRole_value = map[string]int32{
		"WORKSPACE_ROLE_UNSPECIFIED": 0,
		"WORKSPACE_ROLE_USER":        1,
		"WORKSPACE_ROLE_ADMIN":       2,
	}
)

func (x WorkspaceRole) Enum() *WorkspaceRole {
	p := new(WorkspaceRole)
	*p = x
	return p
}

func (x WorkspaceRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceRole) Descriptor() protoreflect.EnumDescriptor {
	return file_workspace_proto_enumTypes[0].Descriptor()
}

func (WorkspaceRole) Type() protoreflect.EnumType {
	return &file_workspace_proto_enumTypes[0]
}

func (x WorkspaceRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceRole.Descriptor instead.
func (WorkspaceRole) EnumDescriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

// Kubernetes-style metadata shared by all top-level OpenShell domain
// objects. Verbatim copy of openshell.datamodel.v1.ObjectMeta.
type ObjectMeta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAtMs         int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	Labels              map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceVersion     uint64                 `protobuf:"varint,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Annotations         map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workspace           string                 `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	DeletionTimestampMs int64                  `protobuf:"varint,8,opt,name=deletion_timestamp_ms,json=deletionTimestampMs,proto3" json:"deletion_timestamp_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetResourceVersion() uint64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ObjectMeta) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ObjectMeta) GetDeletionTimestampMs() int64 {
	if x != nil {
		return x.DeletionTimestampMs
	}
	return 0
}

// Workspace membership record.
type WorkspaceMember struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// OIDC subject claim identifying the principal.
	PrincipalSubject string        `protobuf:"bytes,2,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	Role             WorkspaceRole `protobuf:"varint,3,opt,name=role,proto3,enum=openshell.v1.WorkspaceRole" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkspaceMember) Reset() {
	*x = WorkspaceMember{}
	mi := &file_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMember) ProtoMessage() {}

func (x *WorkspaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMember.ProtoReflect.Descriptor instead.
func (*WorkspaceMember) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceMember) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkspaceMember) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

func (x *WorkspaceMember) GetRole() WorkspaceRole {
	if x != nil {
		return x.Role
	}
	return WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED
}

type AddWorkspaceMemberRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	PrincipalSubject string                 `protobuf:"bytes,2,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	Role             WorkspaceRole          `protobuf:"varint,3,opt,name=role,proto3,enum=openshell.v1.WorkspaceRole" json:"role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddWorkspaceMemberRequest) Reset() {
	*x = AddWorkspaceMemberRequest{}
	mi := &file_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkspaceMemberRequest) ProtoMessage() {}

func (x *AddWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*AddWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *AddWorkspaceMemberRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *AddWorkspaceMemberRequest) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

func (x *AddWorkspaceMemberRequest) GetRole() WorkspaceRole {
	if x != nil {
		return x.Role
	}
	return WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED
}

type AddWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *WorkspaceMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkspaceMemberResponse) Reset() {
	*x = AddWorkspaceMemberResponse{}
	mi := &file_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkspaceMemberResponse) ProtoMessage() {}

func (x *AddWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*AddWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *AddWorkspaceMemberResponse) GetMember() *WorkspaceMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveWorkspaceMemberRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	PrincipalSubject string                 `protobuf:"bytes,2,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveWorkspaceMemberRequest) Reset() {
	*x = RemoveWorkspaceMemberRequest{}
	mi := &file_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkspaceMemberRequest) ProtoMessage() {}

func (x *RemoveWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveWorkspaceMemberRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *RemoveWorkspaceMemberRequest) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

type RemoveWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkspaceMemberResponse) Reset() {
	*x = RemoveWorkspaceMemberResponse{}
	mi := &file_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkspaceMemberResponse) ProtoMessage() {}

func (x *RemoveWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveWorkspaceMemberResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListWorkspaceMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersRequest) Reset() {
	*x = ListWorkspaceMembersRequest{}
	mi := &file_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersRequest) ProtoMessage() {}

func (x *ListWorkspaceMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersRequest) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkspaceMembersRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ListWorkspaceMembersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkspaceMembersRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorkspaceMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*WorkspaceMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersResponse) Reset() {
	*x = ListWorkspaceMembersResponse{}
	mi := &file_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersResponse) ProtoMessage() {}

func (x *ListWorkspaceMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersResponse) Descriptor() ([]byte, []int) {
	return file_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkspaceMembersResponse) GetMembers() []*WorkspaceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_workspace_proto protoreflect.FileDescriptor

const file_workspace_proto_rawDesc = "" +
	"\n" +
	"\x0fworkspace.proto\x12\fopenshell.v1\"\xd7\x03\n" +
	"\n" +
	"ObjectMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12<\n" +
	"\x06labels\x18\x04 \x03(\v2$.openshell.v1.ObjectMeta.LabelsEntryR\x06labels\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\x04R\x0fresourceVersion\x12K\n" +
	"\vannotations\x18\x06 \x03(\v2).openshell.v1.ObjectMeta.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\x122\n" +
	"\x15deletion_timestamp_ms\x18\b \x01(\x03R\x13deletionTimestampMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x0fWorkspaceMember\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.openshell.v1.ObjectMetaR\bmetadata\x12+\n" +
	"\x11principal_subject\x18\x02 \x01(\tR\x10principalSubject\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.openshell.v1.WorkspaceRoleR\x04role\"\x97\x01\n" +
	"\x19AddWorkspaceMemberRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12+\n" +
	"\x11principal_subject\x18\x02 \x01(\tR\x10principalSubject\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.openshell.v1.WorkspaceRoleR\x04role\"S\n" +
	"\x1aAddWorkspaceMemberResponse\x125\n" +
	"\x06member\x18\x01 \x01(\v2\x1d.openshell.v1.WorkspaceMemberR\x06member\"i\n" +
	"\x1cRemoveWorkspaceMemberRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12+\n" +
	"\x11principal_subject\x18\x02 \x01(\tR\x10principalSubject\"9\n" +
	"\x1dRemoveWorkspaceMemberResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"i\n" +
	"\x1bListWorkspaceMembersRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"W\n" +
	"\x1cListWorkspaceMembersResponse\x127\n" +
	"\amembers\x18\x01 \x03(\v2\x1d.openshell.v1.WorkspaceMemberR\amembers*b\n" +
	"\rWorkspaceRole\x12\x1e\n" +
	"\x1aWORKSPACE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WORKSPACE_ROLE_USER\x10\x01\x12\x18\n" +
	"\x14WORKSPACE_ROLE_ADMIN\x10\x022\xd5\x02\n" +
	"\tOpenShell\x12g\n" +
	"\x12AddWorkspaceMember\x12'.openshell.v1.AddWorkspaceMemberRequest\x1a(.openshell.v1.AddWorkspaceMemberResponse\x12p\n" +
	"\x15RemoveWorkspaceMember\x12*.openshell.v1.RemoveWorkspaceMemberRequest\x1a+.openshell.v1.RemoveWorkspaceMemberResponse\x12m\n" +
	"\x14ListWorkspaceMembers\x12).openshell.v1.ListWorkspaceMembersRequest\x1a*.openshell.v1.ListWorkspaceMembersResponseBBZ@github.com/aknochow/ogo/internal/openshellclient;openshellclientb\x06proto3"

var (
	file_workspace_proto_rawDescOnce sync.Once
	file_workspace_proto_rawDescData []byte
)

func file_workspace_proto_rawDescGZIP() []byte {
	file_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)))
	})
	return file_workspace_proto_rawDescData
}

var file_workspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_workspace_proto_goTypes = []any{
	(WorkspaceRole)(0),                    // 0: openshell.v1.WorkspaceRole
	(*ObjectMeta)(nil),                    // 1: openshell.v1.ObjectMeta
	(*WorkspaceMember)(nil),               // 2: openshell.v1.WorkspaceMember
	(*AddWorkspaceMemberRequest)(nil),     // 3: openshell.v1.AddWorkspaceMemberRequest
	(*AddWorkspaceMemberResponse)(nil),    // 4: openshell.v1.AddWorkspaceMemberResponse
	(*RemoveWorkspaceMemberRequest)(nil),  // 5: openshell.v1.RemoveWorkspaceMemberRequest
	(*RemoveWorkspaceMemberResponse)(nil), // 6: openshell.v1.RemoveWorkspaceMemberResponse
	(*ListWorkspaceMembersRequest)(nil),   // 7: openshell.v1.ListWorkspaceMembersRequest
	(*ListWorkspaceMembersResponse)(nil),  // 8: openshell.v1.ListWorkspaceMembersResponse
	nil,                                   // 9: openshell.v1.ObjectMeta.LabelsEntry
	nil,                                   // 10: openshell.v1.ObjectMeta.AnnotationsEntry
}
var file_workspace_proto_depIdxs = []int32{
	9,  // 0: openshell.v1.ObjectMeta.labels:type_name -> openshell.v1.ObjectMeta.LabelsEntry
	10, // 1: openshell.v1.ObjectMeta.annotations:type_name -> openshell.v1.ObjectMeta.AnnotationsEntry
	1,  // 2: openshell.v1.WorkspaceMember.metadata:type_name -> openshell.v1.ObjectMeta
	0,  // 3: openshell.v1.WorkspaceMember.role:type_name -> openshell.v1.WorkspaceRole
	0,  // 4: openshell.v1.AddWorkspaceMemberRequest.role:type_name -> openshell.v1.WorkspaceRole
	2,  // 5: openshell.v1.AddWorkspaceMemberResponse.member:type_name -> openshell.v1.WorkspaceMember
	2,  // 6: openshell.v1.ListWorkspaceMembersResponse.members:type_name -> openshell.v1.WorkspaceMember
	3,  // 7: openshell.v1.OpenShell.AddWorkspaceMember:input_type -> openshell.v1.AddWorkspaceMemberRequest
	5,  // 8: openshell.v1.OpenShell.RemoveWorkspaceMember:input_type -> openshell.v1.RemoveWorkspaceMemberRequest
	7,  // 9: openshell.v1.OpenShell.ListWorkspaceMembers:input_type -> openshell.v1.ListWorkspaceMembersRequest
	4,  // 10: openshell.v1.OpenShell.AddWorkspaceMember:output_type -> openshell.v1.AddWorkspaceMemberResponse
	6,  // 11: openshell.v1.OpenShell.RemoveWorkspaceMember:output_type -> openshell.v1.RemoveWorkspaceMemberResponse
	8,  // 12: openshell.v1.OpenShell.ListWorkspaceMembers:output_type -> openshell.v1.ListWorkspaceMembersResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_workspace_proto_init() }
func file_workspace_proto_init() {
	if File_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_proto_rawDesc), len(file_workspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_proto_depIdxs,
		EnumInfos:         file_workspace_proto_enumTypes,
		MessageInfos:      file_workspace_proto_msgTypes,
	}.Build()
	File_workspace_proto = out.File
	file_workspace_proto_goTypes = nil
	file_workspace_proto_depIdxs = nil
}
