// Minimal client-side subset of the upstream OpenShell gateway's
// openshell.v1.OpenShell gRPC service (github.com/nvidia/openshell,
// proto/openshell.proto + proto/datamodel.proto at the pinned tag
// hack/openshell-pins references) — only the workspace-membership RPCs
// and messages OGO's controller actually calls.
//
// A gRPC client only needs matching method paths and request/response
// message shapes for the RPCs it calls; it doesn't need the rest of the
// service's ~50 other RPCs (sandboxes, providers, drafts, inference,
// etc.) declared here. Field numbers/types below are copied verbatim
// from upstream to preserve wire compatibility — do not renumber.
// Upstream's per-method `option (openshell.options.v1.authorization)`
// annotations are server-side authorization config, not needed by a
// client, and are omitted; see openshell.proto for the real
// requirement (workspace RPCs require a Bearer token with the admin
// role and no explicit scope check today — see
// crates/openshell-server/src/grpc/mod.rs upstream).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: workspace.proto

package openshellclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenShell_AddWorkspaceMember_FullMethodName    = "/openshell.v1.OpenShell/AddWorkspaceMember"
	OpenShell_RemoveWorkspaceMember_FullMethodName = "/openshell.v1.OpenShell/RemoveWorkspaceMember"
	OpenShell_ListWorkspaceMembers_FullMethodName  = "/openshell.v1.OpenShell/ListWorkspaceMembers"
)

// OpenShellClient is the client API for OpenShell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenShellClient interface {
	AddWorkspaceMember(ctx context.Context, in *AddWorkspaceMemberRequest, opts ...grpc.CallOption) (*AddWorkspaceMemberResponse, error)
	RemoveWorkspaceMember(ctx context.Context, in *RemoveWorkspaceMemberRequest, opts ...grpc.CallOption) (*RemoveWorkspaceMemberResponse, error)
	ListWorkspaceMembers(ctx context.Context, in *ListWorkspaceMembersRequest, opts ...grpc.CallOption) (*ListWorkspaceMembersResponse, error)
}

type openShellClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenShellClient(cc grpc.ClientConnInterface) OpenShellClient {
	return &openShellClient{cc}
}

func (c *openShellClient) AddWorkspaceMember(ctx context.Context, in *AddWorkspaceMemberRequest, opts ...grpc.CallOption) (*AddWorkspaceMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWorkspaceMemberResponse)
	err := c.cc.Invoke(ctx, OpenShell_AddWorkspaceMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openShellClient) RemoveWorkspaceMember(ctx context.Context, in *RemoveWorkspaceMemberRequest, opts ...grpc.CallOption) (*RemoveWorkspaceMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWorkspaceMemberResponse)
	err := c.cc.Invoke(ctx, OpenShell_RemoveWorkspaceMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openShellClient) ListWorkspaceMembers(ctx context.Context, in *ListWorkspaceMembersRequest, opts ...grpc.CallOption) (*ListWorkspaceMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspaceMembersResponse)
	err := c.cc.Invoke(ctx, OpenShell_ListWorkspaceMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenShellServer is the server API for OpenShell service.
// All implementations must embed UnimplementedOpenShellServer
// for forward compatibility.
type OpenShellServer interface {
	AddWorkspaceMember(context.Context, *AddWorkspaceMemberRequest) (*AddWorkspaceMemberResponse, error)
	RemoveWorkspaceMember(context.Context, *RemoveWorkspaceMemberRequest) (*RemoveWorkspaceMemberResponse, error)
	ListWorkspaceMembers(context.Context, *ListWorkspaceMembersRequest) (*ListWorkspaceMembersResponse, error)
	mustEmbedUnimplementedOpenShellServer()
}

// UnimplementedOpenShellServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenShellServer struct{}

func (UnimplementedOpenShellServer) AddWorkspaceMember(context.Context, *AddWorkspaceMemberRequest) (*AddWorkspaceMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWorkspaceMember not implemented")
}
func (UnimplementedOpenShellServer) RemoveWorkspaceMember(context.Context, *RemoveWorkspaceMemberRequest) (*RemoveWorkspaceMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorkspaceMember not implemented")
}
func (UnimplementedOpenShellServer) ListWorkspaceMembers(context.Context, *ListWorkspaceMembersRequest) (*ListWorkspaceMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaceMembers not implemented")
}
func (UnimplementedOpenShellServer) mustEmbedUnimplementedOpenShellServer() {}
func (UnimplementedOpenShellServer) testEmbeddedByValue()                   {}

// UnsafeOpenShellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenShellServer will
// result in compilation errors.
type UnsafeOpenShellServer interface {
	mustEmbedUnimplementedOpenShellServer()
}

func RegisterOpenShellServer(s grpc.ServiceRegistrar, srv OpenShellServer) {
	// If the following call panics, it indicates UnimplementedOpenShellServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenShell_ServiceDesc, srv)
}

func _OpenShell_AddWorkspaceMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorkspaceMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenShellServer).AddWorkspaceMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenShell_AddWorkspaceMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenShellServer).AddWorkspaceMember(ctx, req.(*AddWorkspaceMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenShell_RemoveWorkspaceMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorkspaceMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenShellServer).RemoveWorkspaceMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenShell_RemoveWorkspaceMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenShellServer).RemoveWorkspaceMember(ctx, req.(*RemoveWorkspaceMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenShell_ListWorkspaceMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspaceMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenShellServer).ListWorkspaceMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenShell_ListWorkspaceMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenShellServer).ListWorkspaceMembers(ctx, req.(*ListWorkspaceMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenShell_ServiceDesc is the grpc.ServiceDesc for OpenShell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenShell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openshell.v1.OpenShell",
	HandlerType: (*OpenShellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWorkspaceMember",
			Handler:    _OpenShell_AddWorkspaceMember_Handler,
		},
		{
			MethodName: "RemoveWorkspaceMember",
			Handler:    _OpenShell_RemoveWorkspaceMember_Handler,
		},
		{
			MethodName: "ListWorkspaceMembers",
			Handler:    _OpenShell_ListWorkspaceMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace.proto",
}
