apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ogo
  name: ogo-openshellpolicy-admin-role
rules:
- apiGroups:
  - gateway.ogo.aknochow.io
  resources:
  - openshellpolicies
  verbs:
  - '*'
- apiGroups:
  - gateway.ogo.aknochow.io
  resources:
  - openshellpolicies/status
  verbs:
  - get
